### ISSUE TITLE
support for ROS Kinetic

### ISSUE THREAD

**Issue by MaxBaeten** [g/roboteq#16]
Are there any plans to migrate this to ROS Kinetic?

**Comment by rbonghi** [comment]
Hi @MaxBaeten,

I'm following the idea in this repository and I'm writing a new node: https://github.com/rbonghi/roboteq_control

This node use now ros control and you can setup with the dynamic reconfigure all parameters.

At this time this node is unstable, I hope to complete in this month all features and I would like to add in the official repo.

**Comment by MaxBaeten** [comment]
Hi rbonghi, 

Are you still working on this? I plan on making something myself also since the linux api provided by roboteq seems quite well documented. 

But I gladly hear from you when you already have something working!

**Comment by rbonghi** [comment]
Hi @MaxBaeten ,

the linux api it's the same used in my code, in these days I've in plan to use the same code, but the priority is low. If you want work with my code you don't have any problem ;-)

Now the better way to increase the tests with other roboteq board and increase the performance. Now I'm working with only the SDC2130.

I think it's little bit better to open a new issue on my repo.

**Comment by danielj195** [comment]
Hi,

I also have a similar question as to whether this driver will even work with ROS kinetic.  I downloaded driver and followed hex file instructions.  I am able to read data from the motor, but nothing happens when I try to command a position or velocity.  Any help would be greatly appreciated!
