### ISSUE TITLE
Cmake Issue (serialConfig)

### ISSUE THREAD

**Issue by aarontan-git** [g/roboteq#23]
Hello,

I experienced the following issue when I tried to do catkin_make:
---------------------------------------------------------------------------------------------------------------------------------
CMake Warning at /opt/ros/indigo/share/catkin/cmake/catkinConfig.cmake:76 (find_package):
  Could not find a package configuration file provided by "serial" with any
  of the following names:

    serialConfig.cmake
    serial-config.cmake

  Add the installation prefix of "serial" to CMAKE_PREFIX_PATH or set
  "serial_DIR" to a directory containing one of the above files.  If "serial"
  provides a separate development package or SDK, be sure it has been
  installed.
Call Stack (most recent call first):
  roboteq/roboteq_driver/CMakeLists.txt:4 (find_package)

-- Could not find the required component 'serial'. The following CMake error indicates that you either need to install the package with the same name or change your environment so that it can be found.
CMake Error at /opt/ros/indigo/share/catkin/cmake/catkinConfig.cmake:83 (find_package):
  Could not find a package configuration file provided by "serial" with any
  of the following names:

    serialConfig.cmake
    serial-config.cmake

  Add the installation prefix of "serial" to CMAKE_PREFIX_PATH or set
  "serial_DIR" to a directory containing one of the above files.  If "serial"
  provides a separate development package or SDK, be sure it has been
  installed.
Call Stack (most recent call first):
  roboteq/roboteq_driver/CMakeLists.txt:4 (find_package)

Configuring incomplete, errors occurred!
See also "/home/old/catkin_ws/build/CMakeFiles/CMakeOutput.log".
See also "/home/old/catkin_ws/build/CMakeFiles/CMakeError.log".
Invoking "cmake" failed
--------------------------------------------------------------------------------------------------------------------------------

Please help.

Thank you,
Aaron

**Comment by mikepurvis** [comment]
Install `ros-indigo-serial` or add this repo to your workspace: https://github.com/wjwwood/serial
