### ISSUE TITLE
Multi-Channel setBool possible issue

### ISSUE THREAD

**Issue by thomaswatters** [g/roboteq#5]
I was having an issue getting the feedback to display from both channels when launching in in dual channels. I think the issue is in channel.cpp.

>void Channel::timerCallback(const ros::TimerEvent&) {
  if (ros::Time::now() - last_feedback_time_ > ros::Duration(1.0)) {
    // Not receiving feedback, attempt to start it.
    controller_->setUserBool(1, 1);
    controller_->flush();
  }
}

I made the following change:
> void Channel::timerCallback(const ros::TimerEvent&) {
  if (ros::Time::now() - last_feedback_time_ > ros::Duration(1.0)) {
    // Not receiving feedback, attempt to start it.
    controller_->setUserBool(**channel_num_**, 1);
    controller_->flush();
  }
}

not sure if this is correct but it fixed my issue

**Comment by mikepurvis** [comment]
Closed via #6.
